from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render
from HotelApp.models import Hotels
from HotelApp.models import Review
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.forms import ModelForm
from django import forms
