# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageHotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='path',
            field=models.FileField(upload_to=''),
        ),
    ]
