# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=255)),
                ('Country', models.CharField(max_length=255)),
                ('TelephoneNumber', models.IntegerField(default=0)),
                ('ImagePath', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('Description', models.CharField(max_length=255)),
            ],
        ),
    ]
