# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 00:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotels',
            options={'verbose_name_plural': 'Hotels'},
        ),
    ]
