# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='hotel_id',
            new_name='hotel',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='user',
        ),
    ]
