# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authorize', '0002_partners_userrole'),
        ('HotelApp', '0006_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='Partner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Authorize.Partners'),
            preserve_default=False,
        ),
    ]
