# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0008_auto_20170506_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='Description',
            field=models.TextField(max_length=140),
        ),
    ]
